app:
    resource: '@AppBundle/Controller/'
    type: annotation

auth:
    resource: "@AuthBundle/Resources/config/routing/login.yml"

social_auth:
    resource: "@AuthBundle/Resources/config/routing/social.yml"

reset:
    resource: "@AuthBundle/Resources/config/routing/reset.yml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

api_login_check:
    path: /api/login_check

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

page_bundle_api:
    resource: "@PageBundle/Resources/config/routing/api.yml"

auth_bundle_api:
    resource: "@AuthBundle/Resources/config/routing/api.yml"
